name = "BaseOnnx"
uuid = "0c4f4e62-154b-4cad-af80-ba2ac58839d5"
authors = ["Peter Wolf", "Julia Community"]
version = "0.1.0"

[deps]
ProtoBuf = "3349acd9-ac6a-5e09-bcdb-63829b23a429"

[compat]
ProtoBuf = "0.8"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
